### Create Ticket
POST http://localhost:3000/api/newticket
Content-Type: application/json; charset=utf-8

{
"name":"Diana", 
"title":"Fel på Skrivare", 
"description":"Skrivare på station 3 fungerar ej, kommer upp felmeddelande om att den inte hittar nätverk",
"orderNo":20241103,
"itemNo":6667899,
"puoNo":"PUO-240056",
"color": "Medium"
}

### Get all tickets
GET http://localhost:3000/api/tickets


### Get one ticket
GET http://localhost:3000/api/tickets/1


### Delete ticket
DELETE http://localhost:3000/api/tickets/23

### Edit ticket 
PUT http://localhost:3000/api/editticket/1
Content-Type: application/json; charset=utf-8

{
"name":"Leonard", 
"title":"Fel på Skrivare", 
"description":"Skrivare på station 3 fungerar ej, kommer upp felmeddelande om att den inte hittar nätverk",
"orderNo":20241103,
"itemNo":6667899,
"puoNo":"PUO-240056",
"color": "Medium"
}